const GitHub = require('github-api');
const blessed = require('blessed');

const github = new GitHub();
const user = 'SEU_USUARIO_GITHUB';
const repo = 'SEU_REPOSITORIO_GITHUB';

// Cria a tela do jogo usando a biblioteca "blessed"
const screen = blessed.screen({
  smartCSR: true,
  title: 'Cobrinha de Commit no GitHub',
});

// Cria o campo onde a cobrinha irá se movimentar
const field = blessed.box({
  top: 'center',
  left: 'center',
  width: '50%',
  height: '50%',
  content: '',
  tags: true,
  border: {
    type: 'line',
  },
  style: {
    fg: 'white',
    bg: 'black',
    border: {
      fg: '#f0f0f0',
    },
  },
});

// Adiciona o campo na tela do jogo
screen.append(field);

// Define o tamanho da cobrinha
const snakeSize = 5;

// Define a posição inicial da cobrinha
let snake = [
  [10, 10],
  [9, 10],
  [8, 10],
  [7, 10],
  [6, 10],
];

// Define a direção inicial da cobrinha
let direction = 'right';

// Função para obter os commits mais recentes do repositório
async function getCommits() {
  const repository = github.getRepo(user, repo);
  const { data } = await repository.getCommits();
  return data;
}

// Função para atualizar o campo com os commits
async function updateField() {
  const commits = await getCommits();
  const fieldContent = [];
  for (let i = 0; i < field.height - 2; i++) {
    const row = [];
    for (let j = 0; j < field.width - 2; j++) {
      row.push(' ');
    }
    fieldContent.push(row.join(''));
  }
  for (let i = 0; i < commits.length; i++) {
    const commit = commits[i];
    const x = Math.floor((commit.commit.committer.date - Date.now()) / (1000 * 60 * 60 * 24)) + Math.floor(field.width / 2);
    const y = Math.floor(field.height / 2) + i;
    if (x >= 0 && x < field.width - 2 && y >= 0 && y < field.height - 2) {
      fieldContent[y] = fieldContent[y].substr(0, x) + '#' + fieldContent[y].substr(x + 1);
    }
  }
  field.setContent(fieldContent.join('\n'));
  screen.render();
}

// Função para atualizar a posição da cobrinha
function updateSnake() {
  const head = snake[0];
  let newHead;
  switch (direction) {
    case 'right':
      newHead = [head[0] + 1, head[1]];
      break;
    case 'left':
      newHead = [head[
